{{- if not (lookup "v1" "Secret" "a000005" "my-secret") }}
apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  username: {{ include "lookup-test.username" . }}
  password: {{ include "lookup-test.password" . }}
{{- else }}
apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  username: {{ (lookup "v1" "Secret" "a000005" "my-secret").data.username }}
  password: {{ (lookup "v1" "Secret" "a000005" "my-secret").data.password }}
{{- end }}